# Generated by Django 4.2.4 on 2023-08-10 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('like', models.IntegerField(default=0)),
                ('nickname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_nickname', to='users.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Editor_Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('date', models.DateField()),
                ('recruit_date', models.DateField()),
                ('place', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=100)),
                ('like', models.IntegerField(default=0)),
                ('scrap', models.IntegerField(default=0)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='editor_name', to='users.editorprofile')),
            ],
        ),
    ]
