# Generated by Django 4.2.4 on 2023-08-10 22:36

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='editor_post',
            name='scrap',
        ),
        migrations.AddField(
            model_name='editor_post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='posts/'),
        ),
        migrations.AddField(
            model_name='editor_post',
            name='published_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='editor_post',
            name='scarp',
            field=models.ManyToManyField(blank=True, default=0, related_name='scarped_post', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='published_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.RemoveField(
            model_name='editor_post',
            name='like',
        ),
        migrations.RemoveField(
            model_name='post',
            name='like',
        ),
        migrations.AddField(
            model_name='editor_post',
            name='like',
            field=models.ManyToManyField(blank=True, default=0, related_name='editor_liked_post', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='like',
            field=models.ManyToManyField(blank=True, default=0, related_name='liked_post', to=settings.AUTH_USER_MODEL),
        ),
    ]
