# Generated by Django 4.1.7 on 2023-08-13 03:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0002_remove_editor_post_like_remove_post_like_like_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EditorPostLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.editor_post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'post')},
            },
        ),
        migrations.AddField(
            model_name='editor_post',
            name='likes',
            field=models.ManyToManyField(related_name='editor_liked_posts', through='post.EditorPostLike', to=settings.AUTH_USER_MODEL),
        ),
    ]
