# Generated by Django 4.2.4 on 2023-08-10 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_remove_editor_post_scrap_editor_post_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='editor_post',
            name='id',
        ),
        migrations.RemoveField(
            model_name='post',
            name='id',
        ),
        migrations.AddField(
            model_name='editor_post',
            name='ID',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='post',
            name='ID',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
    ]
