# Generated by Django 4.2.4 on 2023-08-10 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_remove_editor_post_id_remove_post_id_editor_post_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='editor_post',
            old_name='name',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='nickname',
            new_name='author',
        ),
    ]
