# Generated by Django 4.2.4 on 2023-08-10 23:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0004_rename_name_editor_post_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editor_post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='editor_name', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_nickname', to=settings.AUTH_USER_MODEL),
        ),
    ]
