# Generated by Django 4.2.4 on 2023-08-14 02:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('uuser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='user_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('nickname', models.CharField(max_length=10)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('address', models.CharField(max_length=100)),
                ('editor_name', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
