# Generated by Django 4.2.4 on 2023-08-14 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='uuser',
            new_name='user',
        ),
    ]
